services:
  wekode.mml.identity.test:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
      args:
        - UID=${UID}
        - GID=${GUID}
        - DOT_NET_BUILD_CONFIG=${DOT_NET_BUILD_CONFIG}
    container_name: wekode.mml.identity.test
    restart: always
    user: ${UID}:${GUID}
    environment:
      INSTANCE: ${INSTANCE}
    volumes:
      - ${VOL_CERTS}:/etc/ssl/certs:ro,z
      - ${APPSETTINGS}:/configs/appsettings.json:ro,Z
      - /etc/localtime:/etc/localtime:ro
    networks:
      - wekode.mml.test
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

networks:
  wekode.mml.test:
    external: true
