services:
  wekode.mml.identity:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    container_name: wekode.mml.identity
    restart: always
    user: ${UID}:${GUID}
    ports:
      - ${PORT}:5051
    volumes:
      - ${VOL_CERTS}:/etc/ssl/certs:ro
      - ${APPSETTINGS}:/appsettings:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - wekode.mml
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

networks:
  wekode.mml:
    external: true
