<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CryptoHelper" Version="4.0.0" />
    <PackageReference Include="Rebus" Version="8.9.0" />
    <PackageReference Include="WeKoDe.MML.Messages" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity.Application\Identity.Application.csproj" />
    <ProjectReference Include="..\Identity.DBContext\Identity.DBContext.csproj" />
  </ItemGroup>

</Project>
